### ISSUE TITLE
[help] Orc.Notifications and VB.Net

### ISSUE THREAD

**Issue by furiousbuilder** [WildGums/Orc.Notifications#2]
Hi,

I'm trying to use Orc.Notifications in my VB.Net application but I don't understand anything in the C# exemple... Can I have help please ? 

Thank you !

**Comment by GeertvanHorrik** [comment]
Can you upload / attach what you have so far? Should be really easy to use this.

There are even online converters available to translate c# code into vb

Sent from my phone, so message is short
________________________________

**Comment by furiousbuilder** [comment]
For now I just have 
Imports Cantel
Imports Catel.IO
Imports Catel.MVVM
Imports Catel.Services
Imports Orc.Notifications

    Class MainWindow
        Public Interface INotification
            Property Title() As String
	    Property Message() As String
	    Property Command() As ICommand
	    Property ShowTime() As TimeSpan
	    Property BorderBrush() As SolidColorBrush
	    Property BackgroundBrush() As SolidColorBrush
	    Property FontBrush() As SolidColorBrush
        End Interface

'There is some code here that I deleted

    End class

I just don't know how to show notifications. Do I need to import another thing ?

**Comment by GeertvanHorrik** [comment]
Resolve INotificationService and use that, should be all

Sent from my phone, so message is short
________________________________

**Comment by furiousbuilder** [comment]
Sorry but how does it looks like ?

**Comment by Khomutov** [comment]
Catel contains very powerful IoC tools. So @GeertvanHorrik means that you should use it to resolve *INotificationService*
Use *ServiceLocator* (which is part of Catel).

**Comment by furiousbuilder** [comment]
Sorry, I'm a bit annoying but have you a sampe ? I never used Catle :/

**Comment by Khomutov** [comment]
getting *ServiceLocator* should be looks like 
``` VB
        Dim serviceLocator = GetServiceLocator()
        Dim notificationService = serviceLocator.ResolveType(Of INotificationService)()
     
       Dim notification = New Notification()
       notification.Message = "your message"

       notificationService.ShowNotification(notification)
```
you just need to configure *notification* variable

**Comment by GeertvanHorrik** [comment]
But there is an example app included?  We also included docs. If that's too complicated, maybe this library is not right for you.

Sent from my phone, so message is short
________________________________

**Comment by furiousbuilder** [comment]
It may be too complicated for me at this time... 
Using you code @Khomutov I got this error in mscorlib.dll : http://pastebin.com/gKfKdf8L

**Comment by GeertvanHorrik** [comment]
I am sorry, we can't help you any further. We provide an example in C#, that's what we support. We have not enough knowledge of VB to provide support for that, sorry.
